mod admission;
mod binary_routes;
mod checker_handoff;
mod long_chain_config;
mod output;
mod parenthesized_routes;
mod result;
mod source_application;
mod source_ast;
mod source_atomic_formula;
mod source_attribute;
mod source_composite_formula;
mod source_context;
mod source_evidence;
mod source_formula;
mod source_formula_composition;
mod source_reserve;
mod source_set_term;
mod source_statement;
mod source_structure;
mod source_term;
mod source_type;
mod type_assertion_routes;

pub(super) use admission::{is_active_type_elaboration, validate_active_type_elaboration_tags};
#[cfg(test)]
pub(super) use binary_routes::{
    SOURCE_CHAINED_LOCAL_MODE_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_CHAINED_LOCAL_MODE_RESERVED_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_CHAINED_LOCAL_MODE_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    SOURCE_CHAINED_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_CHAINED_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_CHAINED_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    SOURCE_DISTINCT_RESERVED_OBJECT_VARIABLE_EQUALITY_CONFIG,
    SOURCE_DISTINCT_RESERVED_OBJECT_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_DISTINCT_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_DISTINCT_RESERVED_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_DISTINCT_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_MODE_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_MODE_RESERVED_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_MODE_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    SOURCE_HETEROGENEOUS_RESERVE_MEMBERSHIP_CONFIG,
    SOURCE_LOCAL_MODE_LONG_CHAIN_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_LOCAL_MODE_LONG_CHAIN_RESERVED_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_LOCAL_MODE_LONG_CHAIN_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    SOURCE_LOCAL_MODE_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_LOCAL_MODE_RESERVED_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_LOCAL_MODE_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_LONG_CHAIN_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_LONG_CHAIN_RESERVED_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_LONG_CHAIN_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    SOURCE_MULTIPLE_OBJECT_RESERVE_DECLARATION_EQUALITY_CONFIG,
    SOURCE_MULTIPLE_OBJECT_RESERVE_DECLARATION_INEQUALITY_CONFIG,
    SOURCE_MULTIPLE_RESERVE_DECLARATION_EQUALITY_CONFIG,
    SOURCE_MULTIPLE_RESERVE_DECLARATION_INEQUALITY_CONFIG,
    SOURCE_MULTIPLE_RESERVE_DECLARATION_MEMBERSHIP_CONFIG,
    SOURCE_RESERVED_OBJECT_VARIABLE_EQUALITY_CONFIG,
    SOURCE_RESERVED_OBJECT_VARIABLE_INEQUALITY_CONFIG, SOURCE_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_RESERVED_VARIABLE_INEQUALITY_CONFIG, SOURCE_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_MODE_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_MODE_RESERVED_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_MODE_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    SOURCE_TWO_EDGE_LOCAL_MODE_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_TWO_EDGE_LOCAL_MODE_RESERVED_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_TWO_EDGE_LOCAL_MODE_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    SOURCE_TWO_EDGE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_TWO_EDGE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_TWO_EDGE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    extract_source_chained_local_mode_reserved_variable_equality,
    extract_source_chained_local_mode_reserved_variable_inequality,
    extract_source_chained_local_mode_reserved_variable_membership,
    extract_source_chained_local_object_mode_reserved_variable_equality,
    extract_source_chained_local_object_mode_reserved_variable_inequality,
    extract_source_chained_local_object_mode_reserved_variable_membership,
    extract_source_distinct_reserved_object_variable_equality,
    extract_source_distinct_reserved_object_variable_inequality,
    extract_source_distinct_reserved_variable_equality,
    extract_source_distinct_reserved_variable_inequality,
    extract_source_distinct_reserved_variable_membership,
    extract_source_four_edge_local_mode_reserved_variable_equality,
    extract_source_four_edge_local_mode_reserved_variable_inequality,
    extract_source_four_edge_local_mode_reserved_variable_membership,
    extract_source_four_edge_local_object_mode_reserved_variable_equality,
    extract_source_four_edge_local_object_mode_reserved_variable_inequality,
    extract_source_four_edge_local_object_mode_reserved_variable_membership,
    extract_source_heterogeneous_reserve_membership,
    extract_source_local_mode_long_chain_reserved_variable_equality,
    extract_source_local_mode_long_chain_reserved_variable_inequality,
    extract_source_local_mode_long_chain_reserved_variable_membership,
    extract_source_local_mode_reserved_variable_equality,
    extract_source_local_mode_reserved_variable_inequality,
    extract_source_local_mode_reserved_variable_membership,
    extract_source_local_object_mode_long_chain_reserved_variable_equality,
    extract_source_local_object_mode_long_chain_reserved_variable_inequality,
    extract_source_local_object_mode_long_chain_reserved_variable_membership,
    extract_source_local_object_mode_reserved_variable_equality,
    extract_source_local_object_mode_reserved_variable_inequality,
    extract_source_local_object_mode_reserved_variable_membership,
    extract_source_multiple_object_reserve_declaration_equality,
    extract_source_multiple_object_reserve_declaration_inequality,
    extract_source_multiple_reserve_declaration_equality,
    extract_source_multiple_reserve_declaration_inequality,
    extract_source_multiple_reserve_declaration_membership,
    extract_source_reserved_object_variable_equality,
    extract_source_reserved_object_variable_inequality, extract_source_reserved_variable_equality,
    extract_source_reserved_variable_inequality, extract_source_reserved_variable_membership,
    extract_source_three_edge_local_mode_reserved_variable_equality,
    extract_source_three_edge_local_mode_reserved_variable_inequality,
    extract_source_three_edge_local_mode_reserved_variable_membership,
    extract_source_three_edge_local_object_mode_reserved_variable_equality,
    extract_source_three_edge_local_object_mode_reserved_variable_inequality,
    extract_source_three_edge_local_object_mode_reserved_variable_membership,
    extract_source_two_edge_local_mode_reserved_variable_equality,
    extract_source_two_edge_local_mode_reserved_variable_inequality,
    extract_source_two_edge_local_mode_reserved_variable_membership,
    extract_source_two_edge_local_object_mode_reserved_variable_equality,
    extract_source_two_edge_local_object_mode_reserved_variable_inequality,
    extract_source_two_edge_local_object_mode_reserved_variable_membership,
    source_chained_local_mode_reserved_variable_equality_output,
    source_chained_local_mode_reserved_variable_inequality_output,
    source_chained_local_mode_reserved_variable_membership_output,
    source_chained_local_object_mode_reserved_variable_equality_output,
    source_chained_local_object_mode_reserved_variable_inequality_output,
    source_chained_local_object_mode_reserved_variable_membership_output,
    source_distinct_reserved_object_variable_equality_output,
    source_distinct_reserved_object_variable_inequality_output,
    source_distinct_reserved_variable_equality_output,
    source_distinct_reserved_variable_inequality_output,
    source_distinct_reserved_variable_membership_output,
    source_four_edge_local_mode_reserved_variable_equality_output,
    source_four_edge_local_mode_reserved_variable_inequality_output,
    source_four_edge_local_mode_reserved_variable_membership_output,
    source_four_edge_local_object_mode_reserved_variable_equality_output,
    source_four_edge_local_object_mode_reserved_variable_inequality_output,
    source_four_edge_local_object_mode_reserved_variable_membership_output,
    source_heterogeneous_reserve_membership_output,
    source_local_mode_long_chain_reserved_variable_equality_output,
    source_local_mode_long_chain_reserved_variable_inequality_output,
    source_local_mode_long_chain_reserved_variable_membership_output,
    source_local_mode_reserved_variable_equality_output,
    source_local_mode_reserved_variable_inequality_output,
    source_local_mode_reserved_variable_membership_output,
    source_local_object_mode_long_chain_reserved_variable_equality_output,
    source_local_object_mode_long_chain_reserved_variable_inequality_output,
    source_local_object_mode_long_chain_reserved_variable_membership_output,
    source_local_object_mode_reserved_variable_equality_output,
    source_local_object_mode_reserved_variable_inequality_output,
    source_local_object_mode_reserved_variable_membership_output,
    source_multiple_object_reserve_declaration_equality_output,
    source_multiple_object_reserve_declaration_inequality_output,
    source_multiple_reserve_declaration_equality_output,
    source_multiple_reserve_declaration_inequality_output,
    source_multiple_reserve_declaration_membership_output,
    source_reserved_object_variable_equality_output,
    source_reserved_object_variable_inequality_output, source_reserved_variable_equality_output,
    source_reserved_variable_inequality_output, source_reserved_variable_membership_output,
    source_three_edge_local_mode_reserved_variable_equality_output,
    source_three_edge_local_mode_reserved_variable_inequality_output,
    source_three_edge_local_mode_reserved_variable_membership_output,
    source_three_edge_local_object_mode_reserved_variable_equality_output,
    source_three_edge_local_object_mode_reserved_variable_inequality_output,
    source_three_edge_local_object_mode_reserved_variable_membership_output,
    source_two_edge_local_mode_reserved_variable_equality_output,
    source_two_edge_local_mode_reserved_variable_inequality_output,
    source_two_edge_local_mode_reserved_variable_membership_output,
    source_two_edge_local_object_mode_reserved_variable_equality_output,
    source_two_edge_local_object_mode_reserved_variable_inequality_output,
    source_two_edge_local_object_mode_reserved_variable_membership_output,
};
pub(super) use binary_routes::{
    source_chained_local_mode_reserved_variable_equality_detail_keys,
    source_chained_local_mode_reserved_variable_inequality_detail_keys,
    source_chained_local_mode_reserved_variable_membership_detail_keys,
    source_chained_local_object_mode_reserved_variable_equality_detail_keys,
    source_chained_local_object_mode_reserved_variable_inequality_detail_keys,
    source_chained_local_object_mode_reserved_variable_membership_detail_keys,
    source_distinct_reserved_object_variable_equality_detail_keys,
    source_distinct_reserved_object_variable_inequality_detail_keys,
    source_distinct_reserved_variable_equality_detail_keys,
    source_distinct_reserved_variable_inequality_detail_keys,
    source_distinct_reserved_variable_membership_detail_keys,
    source_four_edge_local_mode_reserved_variable_equality_detail_keys,
    source_four_edge_local_mode_reserved_variable_inequality_detail_keys,
    source_four_edge_local_mode_reserved_variable_membership_detail_keys,
    source_four_edge_local_object_mode_reserved_variable_equality_detail_keys,
    source_four_edge_local_object_mode_reserved_variable_inequality_detail_keys,
    source_four_edge_local_object_mode_reserved_variable_membership_detail_keys,
    source_heterogeneous_reserve_membership_detail_keys,
    source_local_mode_long_chain_reserved_variable_equality_detail_keys,
    source_local_mode_long_chain_reserved_variable_inequality_detail_keys,
    source_local_mode_long_chain_reserved_variable_membership_detail_keys,
    source_local_mode_reserved_variable_equality_detail_keys,
    source_local_mode_reserved_variable_inequality_detail_keys,
    source_local_mode_reserved_variable_membership_detail_keys,
    source_local_object_mode_long_chain_reserved_variable_equality_detail_keys,
    source_local_object_mode_long_chain_reserved_variable_inequality_detail_keys,
    source_local_object_mode_long_chain_reserved_variable_membership_detail_keys,
    source_local_object_mode_reserved_variable_equality_detail_keys,
    source_local_object_mode_reserved_variable_inequality_detail_keys,
    source_local_object_mode_reserved_variable_membership_detail_keys,
    source_multiple_object_reserve_declaration_equality_detail_keys,
    source_multiple_object_reserve_declaration_inequality_detail_keys,
    source_multiple_reserve_declaration_equality_detail_keys,
    source_multiple_reserve_declaration_inequality_detail_keys,
    source_multiple_reserve_declaration_membership_detail_keys,
    source_reserved_object_variable_equality_detail_keys,
    source_reserved_object_variable_inequality_detail_keys,
    source_reserved_variable_equality_detail_keys, source_reserved_variable_inequality_detail_keys,
    source_reserved_variable_membership_detail_keys,
    source_three_edge_local_mode_reserved_variable_equality_detail_keys,
    source_three_edge_local_mode_reserved_variable_inequality_detail_keys,
    source_three_edge_local_mode_reserved_variable_membership_detail_keys,
    source_three_edge_local_object_mode_reserved_variable_equality_detail_keys,
    source_three_edge_local_object_mode_reserved_variable_inequality_detail_keys,
    source_three_edge_local_object_mode_reserved_variable_membership_detail_keys,
    source_two_edge_local_mode_reserved_variable_equality_detail_keys,
    source_two_edge_local_mode_reserved_variable_inequality_detail_keys,
    source_two_edge_local_mode_reserved_variable_membership_detail_keys,
    source_two_edge_local_object_mode_reserved_variable_equality_detail_keys,
    source_two_edge_local_object_mode_reserved_variable_inequality_detail_keys,
    source_two_edge_local_object_mode_reserved_variable_membership_detail_keys,
};
#[cfg(test)]
pub(super) use checker_handoff::{
    SourceContradictionHandoffCorruption, assemble_source_checker_handoff,
    source_contradiction_handoff_corruption_error,
    source_contradiction_handoff_with_extra_expression,
};
pub(super) use checker_handoff::{
    SourceReserveHandoff, assemble_source_contradiction_checker_handoff,
    assemble_source_reserve_checker_handoff, assert_source_contradiction_handoff,
    assert_source_reserve_core_context_readiness, assert_source_reserve_core_summary_readiness,
    assert_source_reserve_handoff, has_exact_source_contradiction_owner, source_module_binding_env,
};
#[cfg(test)]
pub(super) use output::{
    SourceParenthesizedReservedVariableBinaryFormulaOutput,
    assert_source_reserved_variable_formula_output,
    assert_source_reserved_variable_type_assertion_output,
    build_source_parenthesized_reserved_variable_binary_formula_output,
    build_source_reserved_variable_formula_output,
    build_source_reserved_variable_type_assertion_output,
    source_builtin_type_assertion_formula_output, source_contradiction_formula_output,
    source_formula_connective_quantifier_output, source_formula_statement_output,
    source_imported_attribute_assertion_formula_output,
    source_imported_non_empty_attribute_assertion_formula_output,
    source_imported_predicate_functor_formula_output,
    source_parenthesized_reserved_variable_binary_formula_payload_detail_keys,
    source_reserved_variable_formula_output_detail_keys,
    source_reserved_variable_formula_result_detail_keys,
    source_reserved_variable_type_assertion_result_detail_keys,
    source_set_enumeration_formula_output,
};
pub(super) use output::{
    source_builtin_binary_term_formula_detail_keys,
    source_builtin_type_assertion_formula_detail_keys, source_contradiction_core_ir,
    source_contradiction_core_ir_snapshot, source_contradiction_formula_detail_keys,
    source_formula_connective_quantifier_detail_keys, source_formula_statement_detail_keys,
    source_imported_attribute_assertion_formula_detail_keys,
    source_imported_non_empty_attribute_assertion_formula_detail_keys,
    source_imported_predicate_functor_formula_detail_keys,
    source_set_enumeration_formula_detail_keys,
};
#[cfg(test)]
pub(super) use parenthesized_routes::{
    SOURCE_PARENTHESIZED_HETEROGENEOUS_RESERVE_MEMBERSHIP_CONFIG,
    SOURCE_PARENTHESIZED_RESERVED_OBJECT_VARIABLE_EQUALITY_CONFIG,
    SOURCE_PARENTHESIZED_RESERVED_OBJECT_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_PARENTHESIZED_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_PARENTHESIZED_RESERVED_VARIABLE_INEQUALITY_CONFIG,
    SOURCE_PARENTHESIZED_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    SOURCE_PARENTHESIZED_TWO_EDGE_LOCAL_MODE_RESERVED_VARIABLE_EQUALITY_CONFIG,
    SOURCE_RIGHT_PARENTHESIZED_RESERVED_VARIABLE_MEMBERSHIP_CONFIG,
    assert_source_parenthesized_heterogeneous_reserve_membership_output,
    assert_source_parenthesized_reserved_object_variable_equality_output,
    assert_source_parenthesized_reserved_object_variable_inequality_output,
    assert_source_parenthesized_reserved_variable_equality_output,
    assert_source_parenthesized_reserved_variable_inequality_output,
    assert_source_parenthesized_reserved_variable_membership_output,
    assert_source_parenthesized_two_edge_local_mode_reserved_variable_equality_output,
    assert_source_right_parenthesized_reserved_variable_membership_output,
    extract_source_parenthesized_heterogeneous_reserve_membership,
    extract_source_parenthesized_reserved_object_variable_equality,
    extract_source_parenthesized_reserved_object_variable_inequality,
    extract_source_parenthesized_reserved_variable_equality,
    extract_source_parenthesized_reserved_variable_inequality,
    extract_source_parenthesized_reserved_variable_membership,
    extract_source_parenthesized_two_edge_local_mode_reserved_variable_equality,
    extract_source_right_parenthesized_reserved_variable_membership,
    source_parenthesized_heterogeneous_reserve_membership_output,
    source_parenthesized_heterogeneous_reserve_membership_output_detail_keys,
    source_parenthesized_reserved_object_variable_equality_output,
    source_parenthesized_reserved_object_variable_equality_output_detail_keys,
    source_parenthesized_reserved_object_variable_inequality_output,
    source_parenthesized_reserved_object_variable_inequality_output_detail_keys,
    source_parenthesized_reserved_variable_equality_output,
    source_parenthesized_reserved_variable_equality_output_detail_keys,
    source_parenthesized_reserved_variable_inequality_output,
    source_parenthesized_reserved_variable_inequality_output_detail_keys,
    source_parenthesized_reserved_variable_membership_output,
    source_parenthesized_reserved_variable_membership_output_detail_keys,
    source_parenthesized_two_edge_local_mode_reserved_variable_equality_output,
    source_parenthesized_two_edge_local_mode_reserved_variable_equality_output_detail_keys,
    source_right_parenthesized_reserved_variable_membership_output,
    source_right_parenthesized_reserved_variable_membership_output_detail_keys,
};
pub(super) use parenthesized_routes::{
    source_parenthesized_heterogeneous_reserve_membership_detail_keys,
    source_parenthesized_reserved_object_variable_equality_detail_keys,
    source_parenthesized_reserved_object_variable_inequality_detail_keys,
    source_parenthesized_reserved_variable_equality_detail_keys,
    source_parenthesized_reserved_variable_inequality_detail_keys,
    source_parenthesized_reserved_variable_membership_detail_keys,
    source_parenthesized_two_edge_local_mode_reserved_variable_equality_detail_keys,
    source_right_parenthesized_reserved_variable_membership_detail_keys,
};
pub(super) use result::{
    expected_type_elaboration_detail_keys, type_elaboration_failure_diagnostic,
};
pub(super) use source_application::source_application_transport_detail_keys;
#[cfg(test)]
pub(super) use source_application::{
    SyntheticSourceApplicationOutput, SyntheticSourceFunctorApplication,
    SyntheticSourceFunctorArgument, SyntheticSourceFunctorHead,
    UnwrappedImportedApplicationTestMutation, UnwrappedImportedApplicationTestOptions,
    WrappedImportedApplicationSurfaceMutation, WrappedImportedApplicationTestMutation,
    WrappedImportedApplicationTestOptions, source_application_output,
    source_application_output_with_mutation, synthetic_functional_actual_count,
    synthetic_source_application_output, unwrapped_imported_source_application_handoff_for_test,
    wrapped_imported_source_application_handoff_for_test,
};
#[cfg(test)]
pub(super) use source_ast::{
    direct_token_texts, structural_child_ids, surface_nodes_with_kind, surface_site,
};
pub(super) use source_atomic_formula::source_atomic_formula_transport_detail_keys;
#[cfg(test)]
pub(super) use source_atomic_formula::{
    SourceAtomicFormulaRouteOutput, source_atomic_formula_output,
    source_atomic_formula_output_with_mutation, source_atomic_formula_output_with_source,
    source_atomic_formula_output_with_source_and_mutation,
};
pub(super) use source_attribute::source_attribute_detail_keys;
#[cfg(test)]
pub(super) use source_attribute::{source_attribute_output, synthetic_source_attribute_output};
pub(super) use source_composite_formula::source_composite_formula_transport_detail_keys;
#[cfg(test)]
pub(super) use source_composite_formula::{
    SourceCompositeFormulaRouteOutput, source_composite_formula_output,
    source_composite_formula_output_with_mutation,
};
pub(super) use source_context::source_binding_context_detail_keys;
#[cfg(test)]
pub(super) use source_context::{
    SourceBindingContextRouteOutput, source_binding_context_output,
    source_binding_context_token_shape_is_exact,
};
pub(super) use source_evidence::source_evidence_detail_keys;
#[cfg(test)]
pub(super) use source_evidence::{
    SourceEvidenceRouteKind, source_evidence_output, source_evidence_output_with_mutation,
};
#[cfg(test)]
pub(super) use source_formula::{
    SOURCE_BUILTIN_BINARY_TERM_FORMULA_CONFIGS, SourceParenthesizedOperandSide,
    SourceParenthesizedReservedVariableBinaryFormula, SourceReservedVariableAssertedHeadRelation,
    extract_source_builtin_binary_term_formula, extract_source_builtin_type_assertion_formula,
    extract_source_contradiction_formula, extract_source_formula_connective_grouping,
    extract_source_formula_connective_quantifier, extract_source_formula_nested_quantifier_payload,
    extract_source_formula_quantifier_bound_use, extract_source_formula_statement,
    extract_source_imported_attribute_assertion_formula,
    extract_source_imported_non_empty_attribute_assertion_formula,
    extract_source_imported_predicate_chain_formula,
    extract_source_imported_predicate_functor_formula, extract_source_set_enumeration_formula,
};
pub(super) use source_formula::{
    SourceReservedVariableBinaryFormula, SourceReservedVariableBinaryFormulaConfig,
    SourceReservedVariableBuiltinType, SourceReservedVariableTypeAssertion,
    source_binding_matches_reserved_builtin_type, source_binding_use_ordinals,
    source_mode_terminal_builtin_input, source_reserved_variable_asserted_head_relation_is_exact,
    source_reserved_variable_mode_expansions_are_exact,
    source_type_expression_matches_reserved_builtin_type,
};
pub(super) use source_formula_composition::source_formula_composition_transport_detail_keys;
#[cfg(test)]
pub(super) use source_formula_composition::{
    SourceConditionFormulaCompositionRouteInputs, SourceFormulaCompositionRouteInputs,
    SourceFormulaCompositionRouteOutput, SourcePredicateChainCompositionRouteInputs,
    source_condition_formula_composition_output_with_source,
    source_condition_formula_composition_output_with_source_and_mutation,
    source_formula_composition_output, source_formula_composition_output_with_mutation,
    source_formula_composition_output_with_source,
    source_formula_composition_output_with_source_and_mutation,
    source_predicate_chain_composition_output_with_source,
    source_predicate_chain_composition_output_with_source_and_mutation,
};
pub(super) use source_reserve::extract_builtin_source_reserve_declarations;
#[cfg(test)]
pub(super) use source_reserve::extract_builtin_source_reserve_declarations_after_node_guard;
#[cfg(test)]
pub(super) use source_reserve::{
    resolve_visible_attribute, resolve_visible_type_head, source_mode_symbol_spelling,
};
pub(super) use source_set_term::source_set_term_transport_detail_keys;
#[cfg(test)]
pub(super) use source_set_term::{
    SetEnumerationBindingMutation, SetEnumerationFinalMutation, SetEnumerationHandoffMutation,
    SetEnumerationPrimaryMutation, SetEnumerationProofContextTestOptions,
    SetEnumerationResolverMutation, SetEnumerationSelectionStage, SetEnumerationSurfaceMutation,
    SourceSetTermRouteOutput, SyntheticSourceSetTermDependencies,
    TASK258B3M2B2B3P_BINDING_FIELD_COUNT, TASK258B3M2B2B3P_RESOLVER_FIELD_COUNT,
    set_enumeration_proof_context_handoff_for_test, set_enumeration_selection_stage_for_test,
    source_set_term_output, source_set_term_output_with_mutation,
    source_set_term_output_with_source, source_set_term_output_with_source_and_mutation,
    synthetic_source_set_term_output, synthetic_source_set_term_output_with_mutation,
};
pub(super) use source_statement::source_statement_transport_detail_keys;
#[cfg(test)]
pub(super) use source_statement::{
    SOURCE_STATEMENT_B1_TEXT, SOURCE_STATEMENT_B2_TEXT, SOURCE_STATEMENT_B3_TEXT,
    SOURCE_STATEMENT_B3M1_TEXT, SOURCE_STATEMENT_B3M2A_TEXT, SOURCE_STATEMENT_B3M2B1_TEXT,
    SOURCE_STATEMENT_B3M2B2A_TEXT, SOURCE_STATEMENT_B3M2B2B1A_TEXT,
    SOURCE_STATEMENT_B3M2B2B1B1_TEXT, SOURCE_STATEMENT_B3M2B2B2A_TEXT,
    SOURCE_STATEMENT_B3M2B2B2B_TEXT, SOURCE_STATEMENT_B3M2B2B2C_TEXT,
    SOURCE_STATEMENT_B3M2B2B3A_TEXT, SOURCE_STATEMENT_B3M2B2B3B_TEXT,
    SOURCE_STATEMENT_B3M2B2B3C_TEXT, SOURCE_STATEMENT_B3N_TEXT, SOURCE_STATEMENT_TEXT,
    SourceStatementB1Extraction, SourceStatementB2Extraction, SourceStatementB3Extraction,
    SourceStatementB3M1Extraction, SourceStatementB3M1RouteInputs, SourceStatementB3M2AExtraction,
    SourceStatementB3M2ARouteInputs, SourceStatementB3M2B1Extraction,
    SourceStatementB3M2B1RouteInputs, SourceStatementB3M2B2AExtraction,
    SourceStatementB3M2B2ARouteInputs, SourceStatementB3M2B2B1AExtraction,
    SourceStatementB3M2B2B1ARouteInputs, SourceStatementB3M2B2B1B1Extraction,
    SourceStatementB3M2B2B1B1RouteInputs, SourceStatementB3M2B2B2AExtraction,
    SourceStatementB3M2B2B2ARouteInputs, SourceStatementB3M2B2B2BExtraction,
    SourceStatementB3M2B2B2BRouteInputs, SourceStatementB3M2B2B2CExtraction,
    SourceStatementB3M2B2B2CRouteInputs, SourceStatementB3M2B2B3AExtraction,
    SourceStatementB3M2B2B3ARouteInputs, SourceStatementB3M2B2B3AStage,
    SourceStatementB3M2B2B3ASurfaceMutation, SourceStatementB3M2B2B3BExtraction,
    SourceStatementB3M2B2B3BLowerStage, SourceStatementB3M2B2B3BRouteInputs,
    SourceStatementB3M2B2B3BStage, SourceStatementB3M2B2B3BSurfaceMutation,
    SourceStatementB3M2B2B3CExtraction, SourceStatementB3M2B2B3CLowerStage,
    SourceStatementB3M2B2B3CRouteInputs, SourceStatementB3M2B2B3CStage,
    SourceStatementB3M2B2B3CSurfaceMutation, SourceStatementB3NExtraction,
    SourceStatementB3NRouteInputs, SourceStatementB3RouteInputs, SourceStatementExtraction,
    SourceStatementRouteInputs, SourceStatementRouteOutput, TASK258B3M2B2B3A_TASK256_FIELD_COUNT,
    TASK258B3M2B2B3A_TASK258_FIELD_COUNT, TASK258B3M2B2B3A_WITNESS_FIELD_COUNT,
    TASK258B3M2B2B3B_TASK48_FIELD_COUNT, TASK258B3M2B2B3B_TASK252_FIELD_COUNT,
    TASK258B3M2B2B3B_TASK255_FIELD_COUNT, TASK258B3M2B2B3B_TASK256_FIELD_COUNT,
    TASK258B3M2B2B3B_TASK258_FIELD_COUNT, TASK258B3M2B2B3B_WITNESS_FIELD_COUNT,
    TASK258B3M2B2B3C_TASK48_FIELD_COUNT, TASK258B3M2B2B3C_TASK252_FIELD_COUNT,
    TASK258B3M2B2B3C_TASK255_FIELD_COUNT, TASK258B3M2B2B3C_TASK256_FIELD_COUNT,
    TASK258B3M2B2B3C_TASK258_FIELD_COUNT, TASK258B3M2B2B3C_WITNESS_FIELD_COUNT,
    extract_application_witness_source_statement, extract_choice_witness_source_statement,
    extract_choice_witness_source_statement_with_surface_mutation,
    extract_empty_set_enumeration_witness_source_statement,
    extract_empty_set_enumeration_witness_source_statement_with_surface_mutation,
    extract_multiple_witness_source_statement, extract_named_witness_source_statement,
    extract_nested_parenthesized_witness_source_statement, extract_nested_source_statement,
    extract_numeral_witness_source_statement, extract_parenthesized_witness_source_statement,
    extract_set_enumeration_witness_source_statement,
    extract_set_enumeration_witness_source_statement_with_surface_mutation,
    extract_single_assumption_source_statement, extract_single_witness_source_statement,
    extract_source_reserved_variable_theorem_statement,
    extract_structure_constructor_witness_source_statement,
    extract_structure_selector_witness_source_statement,
    extract_structure_update_witness_source_statement,
    extract_wrapped_application_witness_source_statement, source_statement_b1_output_with_mutation,
    source_statement_b2_output_with_mutation, source_statement_b2_output_with_resolver_mutation,
    source_statement_b3_output_with_mutation, source_statement_b3_output_with_resolver_mutation,
    source_statement_b3_resolver_env_for_test, source_statement_b3m1_output_with_mutation,
    source_statement_b3m1_output_with_resolver_mutation,
    source_statement_b3m1_resolver_env_for_test, source_statement_b3m2a_output_with_mutation,
    source_statement_b3m2a_output_with_resolver_mutation,
    source_statement_b3m2a_resolver_env_for_test, source_statement_b3m2b1_output_with_mutation,
    source_statement_b3m2b1_output_with_resolver_mutation,
    source_statement_b3m2b1_resolver_env_for_test, source_statement_b3m2b2a_output_with_mutation,
    source_statement_b3m2b2a_output_with_resolver_mutation,
    source_statement_b3m2b2a_resolver_env_for_test,
    source_statement_b3m2b2b1a_output_with_mutation,
    source_statement_b3m2b2b1a_output_with_resolver_mutation,
    source_statement_b3m2b2b1a_resolver_env_for_test,
    source_statement_b3m2b2b1b1_output_with_mutation,
    source_statement_b3m2b2b1b1_output_with_resolver_mutation,
    source_statement_b3m2b2b1b1_resolver_env_for_test,
    source_statement_b3m2b2b2a_output_with_mutation,
    source_statement_b3m2b2b2a_output_with_resolver_mutation,
    source_statement_b3m2b2b2a_resolver_env_for_test,
    source_statement_b3m2b2b2b_output_with_mutation,
    source_statement_b3m2b2b2b_output_with_resolver_mutation,
    source_statement_b3m2b2b2b_resolver_env_for_test,
    source_statement_b3m2b2b2c_output_with_mutation,
    source_statement_b3m2b2b2c_output_with_resolver_mutation,
    source_statement_b3m2b2b2c_resolver_env_for_test,
    source_statement_b3m2b2b3a_output_with_mutation,
    source_statement_b3m2b2b3a_output_with_post_auth_family_mutation,
    source_statement_b3m2b2b3a_output_with_resolver_mutation,
    source_statement_b3m2b2b3a_output_with_stage_mutation,
    source_statement_b3m2b2b3a_resolver_env_for_test,
    source_statement_b3m2b2b3b_output_with_lower_stage_mutation,
    source_statement_b3m2b2b3b_output_with_mutation,
    source_statement_b3m2b2b3b_output_with_post_auth_family_mutation,
    source_statement_b3m2b2b3b_output_with_resolver_mutation,
    source_statement_b3m2b2b3b_output_with_stage_mutation,
    source_statement_b3m2b2b3b_resolver_env_for_test,
    source_statement_b3m2b2b3c_output_with_lower_stage_mutation,
    source_statement_b3m2b2b3c_output_with_mutation,
    source_statement_b3m2b2b3c_output_with_post_auth_family_mutation,
    source_statement_b3m2b2b3c_output_with_resolver_mutation,
    source_statement_b3m2b2b3c_output_with_stage_mutation,
    source_statement_b3m2b2b3c_resolver_env_for_test, source_statement_b3n_output_with_mutation,
    source_statement_b3n_output_with_resolver_mutation, source_statement_b3n_resolver_env_for_test,
    source_statement_output_with_resolver_mutation, source_statement_output_with_source,
    source_statement_output_with_source_and_mutation, source_statement_resolver_env_for_test,
};
pub(super) use source_structure::source_structure_transport_detail_keys;
#[cfg(test)]
pub(super) use source_structure::{
    ImportedStructureConstructorSurfaceMutation, ImportedStructureConstructorTestMutation,
    ImportedStructureConstructorTestOptions, ImportedStructureSelectorSurfaceMutation,
    ImportedStructureSelectorTestMutation, ImportedStructureSelectorTestOptions,
    ImportedStructureUpdateSurfaceMutation, ImportedStructureUpdateTestMutation,
    ImportedStructureUpdateTestOptions, SourceStructureRouteOutput,
    SyntheticSourceStructureDependencies, imported_structure_constructor_handoff_for_test,
    imported_structure_selector_handoff_for_test, imported_structure_update_handoff_for_test,
    source_structure_output, source_structure_output_with_mutation,
    synthetic_source_structure_output, synthetic_source_structure_output_with_mutation,
    synthetic_source_structure_output_with_validation_symbols,
};
pub(super) use source_term::source_term_transport_error_detail_keys;
#[cfg(test)]
pub(super) use source_term::{
    source_term_output, source_term_output_with_mutation, synthetic_source_term_output,
};
pub(super) use source_type::source_type_application_detail_keys;
#[cfg(test)]
pub(super) use source_type::source_type_application_output;
#[cfg(test)]
pub(super) use type_assertion_routes::{
    SOURCE_CHAINED_LOCAL_MODE_ASSERTED_HEAD_CONFIG,
    SOURCE_CHAINED_LOCAL_MODE_RADIX_ASSERTED_HEAD_CONFIG,
    SOURCE_CHAINED_LOCAL_MODE_RESERVED_VARIABLE_TYPE_ASSERTION_CONFIG,
    SOURCE_CHAINED_LOCAL_OBJECT_MODE_ASSERTED_HEAD_CONFIG,
    SOURCE_CHAINED_LOCAL_OBJECT_MODE_RADIX_ASSERTED_HEAD_CONFIG,
    SOURCE_CHAINED_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_TYPE_ASSERTION_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_MODE_ASSERTED_HEAD_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_MODE_FOUR_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_MODE_RADIX_ASSERTED_HEAD_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_MODE_RESERVED_VARIABLE_TYPE_ASSERTION_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_MODE_THREE_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_MODE_TWO_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_OBJECT_MODE_ASSERTED_HEAD_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_OBJECT_MODE_FOUR_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_OBJECT_MODE_RADIX_ASSERTED_HEAD_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_TYPE_ASSERTION_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_OBJECT_MODE_THREE_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_FOUR_EDGE_LOCAL_OBJECT_MODE_TWO_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_MODE_ASSERTED_HEAD_CONFIG, SOURCE_LOCAL_MODE_LONG_CHAIN_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_MODE_LONG_CHAIN_FIVE_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_MODE_LONG_CHAIN_FOUR_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_MODE_LONG_CHAIN_RADIX_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_MODE_LONG_CHAIN_RESERVED_VARIABLE_TYPE_ASSERTION_CONFIG,
    SOURCE_LOCAL_MODE_LONG_CHAIN_SIX_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_MODE_LONG_CHAIN_THREE_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_MODE_LONG_CHAIN_TWO_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_MODE_RESERVED_VARIABLE_TYPE_ASSERTION_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_LONG_CHAIN_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_LONG_CHAIN_FIVE_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_LONG_CHAIN_FOUR_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_LONG_CHAIN_RADIX_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_LONG_CHAIN_RESERVED_VARIABLE_TYPE_ASSERTION_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_LONG_CHAIN_SIX_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_LONG_CHAIN_THREE_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_LONG_CHAIN_TWO_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_TYPE_ASSERTION_CONFIG,
    SOURCE_RESERVED_OBJECT_VARIABLE_TYPE_ASSERTION_CONFIG,
    SOURCE_RESERVED_VARIABLE_TYPE_ASSERTION_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_MODE_ASSERTED_HEAD_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_MODE_RADIX_ASSERTED_HEAD_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_MODE_RESERVED_VARIABLE_TYPE_ASSERTION_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_MODE_THREE_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_MODE_TWO_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_OBJECT_MODE_ASSERTED_HEAD_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_OBJECT_MODE_RADIX_ASSERTED_HEAD_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_TYPE_ASSERTION_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_OBJECT_MODE_THREE_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_THREE_EDGE_LOCAL_OBJECT_MODE_TWO_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_TWO_EDGE_LOCAL_MODE_ASSERTED_HEAD_CONFIG,
    SOURCE_TWO_EDGE_LOCAL_MODE_RADIX_ASSERTED_HEAD_CONFIG,
    SOURCE_TWO_EDGE_LOCAL_MODE_RESERVED_VARIABLE_TYPE_ASSERTION_CONFIG,
    SOURCE_TWO_EDGE_LOCAL_MODE_TWO_HOP_ASSERTED_HEAD_CONFIG,
    SOURCE_TWO_EDGE_LOCAL_OBJECT_MODE_ASSERTED_HEAD_CONFIG,
    SOURCE_TWO_EDGE_LOCAL_OBJECT_MODE_RADIX_ASSERTED_HEAD_CONFIG,
    SOURCE_TWO_EDGE_LOCAL_OBJECT_MODE_RESERVED_VARIABLE_TYPE_ASSERTION_CONFIG,
    SOURCE_TWO_EDGE_LOCAL_OBJECT_MODE_TWO_HOP_ASSERTED_HEAD_CONFIG,
    extract_source_chained_local_mode_asserted_head,
    extract_source_chained_local_mode_radix_asserted_head,
    extract_source_chained_local_mode_reserved_variable_type_assertion,
    extract_source_chained_local_object_mode_asserted_head,
    extract_source_chained_local_object_mode_radix_asserted_head,
    extract_source_chained_local_object_mode_reserved_variable_type_assertion,
    extract_source_four_edge_local_mode_asserted_head,
    extract_source_four_edge_local_mode_four_hop_asserted_head,
    extract_source_four_edge_local_mode_radix_asserted_head,
    extract_source_four_edge_local_mode_reserved_variable_type_assertion,
    extract_source_four_edge_local_mode_three_hop_asserted_head,
    extract_source_four_edge_local_mode_two_hop_asserted_head,
    extract_source_four_edge_local_object_mode_asserted_head,
    extract_source_four_edge_local_object_mode_four_hop_asserted_head,
    extract_source_four_edge_local_object_mode_radix_asserted_head,
    extract_source_four_edge_local_object_mode_reserved_variable_type_assertion,
    extract_source_four_edge_local_object_mode_three_hop_asserted_head,
    extract_source_four_edge_local_object_mode_two_hop_asserted_head,
    extract_source_local_mode_asserted_head, extract_source_local_mode_long_chain_asserted_head,
    extract_source_local_mode_long_chain_five_hop_asserted_head,
    extract_source_local_mode_long_chain_four_hop_asserted_head,
    extract_source_local_mode_long_chain_radix_asserted_head,
    extract_source_local_mode_long_chain_reserved_variable_type_assertion,
    extract_source_local_mode_long_chain_six_hop_asserted_head,
    extract_source_local_mode_long_chain_three_hop_asserted_head,
    extract_source_local_mode_long_chain_two_hop_asserted_head,
    extract_source_local_mode_reserved_variable_type_assertion,
    extract_source_local_object_mode_asserted_head,
    extract_source_local_object_mode_long_chain_asserted_head,
    extract_source_local_object_mode_long_chain_five_hop_asserted_head,
    extract_source_local_object_mode_long_chain_four_hop_asserted_head,
    extract_source_local_object_mode_long_chain_radix_asserted_head,
    extract_source_local_object_mode_long_chain_reserved_variable_type_assertion,
    extract_source_local_object_mode_long_chain_six_hop_asserted_head,
    extract_source_local_object_mode_long_chain_three_hop_asserted_head,
    extract_source_local_object_mode_long_chain_two_hop_asserted_head,
    extract_source_local_object_mode_reserved_variable_type_assertion,
    extract_source_reserved_object_variable_type_assertion,
    extract_source_reserved_variable_type_assertion,
    extract_source_three_edge_local_mode_asserted_head,
    extract_source_three_edge_local_mode_radix_asserted_head,
    extract_source_three_edge_local_mode_reserved_variable_type_assertion,
    extract_source_three_edge_local_mode_three_hop_asserted_head,
    extract_source_three_edge_local_mode_two_hop_asserted_head,
    extract_source_three_edge_local_object_mode_asserted_head,
    extract_source_three_edge_local_object_mode_radix_asserted_head,
    extract_source_three_edge_local_object_mode_reserved_variable_type_assertion,
    extract_source_three_edge_local_object_mode_three_hop_asserted_head,
    extract_source_three_edge_local_object_mode_two_hop_asserted_head,
    extract_source_two_edge_local_mode_asserted_head,
    extract_source_two_edge_local_mode_radix_asserted_head,
    extract_source_two_edge_local_mode_reserved_variable_type_assertion,
    extract_source_two_edge_local_mode_two_hop_asserted_head,
    extract_source_two_edge_local_object_mode_asserted_head,
    extract_source_two_edge_local_object_mode_radix_asserted_head,
    extract_source_two_edge_local_object_mode_reserved_variable_type_assertion,
    extract_source_two_edge_local_object_mode_two_hop_asserted_head,
    source_chained_local_mode_asserted_head_output,
    source_chained_local_mode_radix_asserted_head_output,
    source_chained_local_mode_reserved_variable_type_assertion_output,
    source_chained_local_object_mode_asserted_head_output,
    source_chained_local_object_mode_radix_asserted_head_output,
    source_chained_local_object_mode_reserved_variable_type_assertion_output,
    source_four_edge_local_mode_asserted_head_output,
    source_four_edge_local_mode_four_hop_asserted_head_output,
    source_four_edge_local_mode_radix_asserted_head_output,
    source_four_edge_local_mode_reserved_variable_type_assertion_output,
    source_four_edge_local_mode_three_hop_asserted_head_output,
    source_four_edge_local_mode_two_hop_asserted_head_output,
    source_four_edge_local_object_mode_asserted_head_output,
    source_four_edge_local_object_mode_four_hop_asserted_head_output,
    source_four_edge_local_object_mode_radix_asserted_head_output,
    source_four_edge_local_object_mode_reserved_variable_type_assertion_output,
    source_four_edge_local_object_mode_three_hop_asserted_head_output,
    source_four_edge_local_object_mode_two_hop_asserted_head_output,
    source_local_mode_asserted_head_output, source_local_mode_long_chain_asserted_head_output,
    source_local_mode_long_chain_five_hop_asserted_head_output,
    source_local_mode_long_chain_four_hop_asserted_head_output,
    source_local_mode_long_chain_radix_asserted_head_output,
    source_local_mode_long_chain_reserved_variable_type_assertion_output,
    source_local_mode_long_chain_six_hop_asserted_head_output,
    source_local_mode_long_chain_three_hop_asserted_head_output,
    source_local_mode_long_chain_two_hop_asserted_head_output,
    source_local_mode_reserved_variable_type_assertion_output,
    source_local_object_mode_asserted_head_output,
    source_local_object_mode_long_chain_asserted_head_output,
    source_local_object_mode_long_chain_five_hop_asserted_head_output,
    source_local_object_mode_long_chain_four_hop_asserted_head_output,
    source_local_object_mode_long_chain_radix_asserted_head_output,
    source_local_object_mode_long_chain_reserved_variable_type_assertion_output,
    source_local_object_mode_long_chain_six_hop_asserted_head_output,
    source_local_object_mode_long_chain_three_hop_asserted_head_output,
    source_local_object_mode_long_chain_two_hop_asserted_head_output,
    source_local_object_mode_reserved_variable_type_assertion_output,
    source_reserved_object_variable_type_assertion_output,
    source_reserved_variable_type_assertion_output,
    source_three_edge_local_mode_asserted_head_output,
    source_three_edge_local_mode_radix_asserted_head_output,
    source_three_edge_local_mode_reserved_variable_type_assertion_output,
    source_three_edge_local_mode_three_hop_asserted_head_output,
    source_three_edge_local_mode_two_hop_asserted_head_output,
    source_three_edge_local_object_mode_asserted_head_output,
    source_three_edge_local_object_mode_radix_asserted_head_output,
    source_three_edge_local_object_mode_reserved_variable_type_assertion_output,
    source_three_edge_local_object_mode_three_hop_asserted_head_output,
    source_three_edge_local_object_mode_two_hop_asserted_head_output,
    source_two_edge_local_mode_asserted_head_output,
    source_two_edge_local_mode_radix_asserted_head_output,
    source_two_edge_local_mode_reserved_variable_type_assertion_output,
    source_two_edge_local_mode_two_hop_asserted_head_output,
    source_two_edge_local_object_mode_asserted_head_output,
    source_two_edge_local_object_mode_radix_asserted_head_output,
    source_two_edge_local_object_mode_reserved_variable_type_assertion_output,
    source_two_edge_local_object_mode_two_hop_asserted_head_output,
};
pub(super) use type_assertion_routes::{
    source_chained_local_mode_asserted_head_detail_keys,
    source_chained_local_mode_radix_asserted_head_detail_keys,
    source_chained_local_mode_reserved_variable_type_assertion_detail_keys,
    source_chained_local_object_mode_asserted_head_detail_keys,
    source_chained_local_object_mode_radix_asserted_head_detail_keys,
    source_chained_local_object_mode_reserved_variable_type_assertion_detail_keys,
    source_four_edge_local_mode_asserted_head_detail_keys,
    source_four_edge_local_mode_four_hop_asserted_head_detail_keys,
    source_four_edge_local_mode_radix_asserted_head_detail_keys,
    source_four_edge_local_mode_reserved_variable_type_assertion_detail_keys,
    source_four_edge_local_mode_three_hop_asserted_head_detail_keys,
    source_four_edge_local_mode_two_hop_asserted_head_detail_keys,
    source_four_edge_local_object_mode_asserted_head_detail_keys,
    source_four_edge_local_object_mode_four_hop_asserted_head_detail_keys,
    source_four_edge_local_object_mode_radix_asserted_head_detail_keys,
    source_four_edge_local_object_mode_reserved_variable_type_assertion_detail_keys,
    source_four_edge_local_object_mode_three_hop_asserted_head_detail_keys,
    source_four_edge_local_object_mode_two_hop_asserted_head_detail_keys,
    source_local_mode_asserted_head_detail_keys,
    source_local_mode_long_chain_asserted_head_detail_keys,
    source_local_mode_long_chain_five_hop_asserted_head_detail_keys,
    source_local_mode_long_chain_four_hop_asserted_head_detail_keys,
    source_local_mode_long_chain_radix_asserted_head_detail_keys,
    source_local_mode_long_chain_reserved_variable_type_assertion_detail_keys,
    source_local_mode_long_chain_six_hop_asserted_head_detail_keys,
    source_local_mode_long_chain_three_hop_asserted_head_detail_keys,
    source_local_mode_long_chain_two_hop_asserted_head_detail_keys,
    source_local_mode_reserved_variable_type_assertion_detail_keys,
    source_local_object_mode_asserted_head_detail_keys,
    source_local_object_mode_long_chain_asserted_head_detail_keys,
    source_local_object_mode_long_chain_five_hop_asserted_head_detail_keys,
    source_local_object_mode_long_chain_four_hop_asserted_head_detail_keys,
    source_local_object_mode_long_chain_radix_asserted_head_detail_keys,
    source_local_object_mode_long_chain_reserved_variable_type_assertion_detail_keys,
    source_local_object_mode_long_chain_six_hop_asserted_head_detail_keys,
    source_local_object_mode_long_chain_three_hop_asserted_head_detail_keys,
    source_local_object_mode_long_chain_two_hop_asserted_head_detail_keys,
    source_local_object_mode_reserved_variable_type_assertion_detail_keys,
    source_reserved_object_variable_type_assertion_detail_keys,
    source_reserved_variable_type_assertion_detail_keys,
    source_three_edge_local_mode_asserted_head_detail_keys,
    source_three_edge_local_mode_radix_asserted_head_detail_keys,
    source_three_edge_local_mode_reserved_variable_type_assertion_detail_keys,
    source_three_edge_local_mode_three_hop_asserted_head_detail_keys,
    source_three_edge_local_mode_two_hop_asserted_head_detail_keys,
    source_three_edge_local_object_mode_asserted_head_detail_keys,
    source_three_edge_local_object_mode_radix_asserted_head_detail_keys,
    source_three_edge_local_object_mode_reserved_variable_type_assertion_detail_keys,
    source_three_edge_local_object_mode_three_hop_asserted_head_detail_keys,
    source_three_edge_local_object_mode_two_hop_asserted_head_detail_keys,
    source_two_edge_local_mode_asserted_head_detail_keys,
    source_two_edge_local_mode_radix_asserted_head_detail_keys,
    source_two_edge_local_mode_reserved_variable_type_assertion_detail_keys,
    source_two_edge_local_mode_two_hop_asserted_head_detail_keys,
    source_two_edge_local_object_mode_asserted_head_detail_keys,
    source_two_edge_local_object_mode_radix_asserted_head_detail_keys,
    source_two_edge_local_object_mode_reserved_variable_type_assertion_detail_keys,
    source_two_edge_local_object_mode_two_hop_asserted_head_detail_keys,
};
