definition
  mode BaseObjectModeDef: BaseObjectMode is object;
end;

definition
  mode InnerObjectModeDef: InnerObjectMode is BaseObjectMode;
end;

definition
  mode MiddleObjectModeDef: MiddleObjectMode is InnerObjectMode;
end;

definition
  mode OuterObjectModeDef: OuterObjectMode is MiddleObjectMode;
end;

definition
  mode TooDeepObjectModeDef: TooDeepObjectMode is OuterObjectMode;
end;

reserve z for TooDeepObjectMode;
