definition
  let X be set;
  attr OAADef: X is oamarked means X = X;
  attr OBBDef: X is obmarked means X = X;
end;

registration
  cluster OAExists: oamarked set;
  existence proof
    take the set;
    thus the set is oamarked by OAADef;
  end;
  cluster OBExists: obmarked set;
  existence proof
    take the set;
    thus the set is obmarked by OBBDef;
  end;
  cluster OABExists: oamarked obmarked set;
  existence proof
    take the set;
    thus the set is oamarked obmarked by OAADef, OBBDef;
  end;
end;

definition
  let X be oamarked set;
  func Ov3Def: ovpick X -> set equals X;
  coherence;
end;

definition
  let X be obmarked set;
  func Ov4Def: ovpick X -> set equals X;
  coherence;
end;

theorem OvBad1: for X being oamarked obmarked set holds ovpick X = X
proof
  let X be oamarked obmarked set;
  thus ovpick X = X;
end;
